In [7]:
import pandas as pd
df=pd.read_csv("diabetes_data.csv")
df.shape
df.columns
df.dtypes

user_id                   int64
date                     object
weight                  float64
height                  float64
blood_glucose           float64
physical_activity       float64
diet                      int64
medication_adherence      int64
stress_level              int64
sleep_hours             float64
hydration_level           int64
bmi                     float64
risk_score              float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1000 non-null   int64
 1   date                  1000 non-null   object
 2   weight                1000 non-null   float64
 3   height                1000 non-null   float64
 4   blood_glucose         1000 non-null   float64
 5   physical_activity     1000 non-null   float64
 6   diet                  1000 non-null   int64
 7   medication_adherence  1000 non-null   int64
 8   stress_level          1000 non-null   int64
 9   sleep_hours           1000 non-null   float64
 10  hydration_level       1000 non-null   int64
 11  bmi                   1000 non-null   float64
 12  risk_score            1000 non-null   float64
dtypes: float64(7), int64(5), object(1)
memory usage: 101.7+ KB

In [9]:
df.describe()

,user_id,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,70.361797,170.795375,140.818899,30.294497,0.604000,0.69300,0.950000,7.076312,0.710000,24.385500,36.422120
std,288.819436,14.467165,9.742934,38.064177,19.305165,0.489309,0.46148,0.833183,1.883829,0.453989,5.872022,14.898022
min,1.000000,40.000000,150.000000,70.000000,0.000000,0.000000,0.00000,0.000000,4.000000,0.000000,10.900000,0.000000
25%,250.750000,60.286145,163.937583,114.080015,15.251591,0.000000,0.00000,0.000000,5.688762,0.000000,20.100000,25.746352
50%,500.500000,70.379509,170.630771,139.989969,30.003691,1.000000,1.00000,1.000000,6.998834,1.000000,24.100000,36.086756
75%,750.250000,79.719158,177.288822,166.436613,43.338908,1.000000,1.00000,2.000000,8.391989,1.000000,28.225000,46.402982
max,1000.000000,120.000000,200.000000,297.049508,94.861859,1.000000,1.00000,2.000000,12.000000,1.000000,45.200000,78.745396

In [11]:
df.isnull().sum()

user_id                 0
date                    0
weight                  0
height                  0
blood_glucose           0
physical_activity       0
diet                    0
medication_adherence    0
stress_level            0
sleep_hours             0
hydration_level         0
bmi                     0
risk_score              0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1000 non-null   int64
 1   date                  1000 non-null   object
 2   weight                1000 non-null   float64
 3   height                1000 non-null   float64
 4   blood_glucose         1000 non-null   float64
 5   physical_activity     1000 non-null   float64
 6   diet                  1000 non-null   int64
 7   medication_adherence  1000 non-null   int64
 8   stress_level          1000 non-null   int64
 9   sleep_hours           1000 non-null   float64
 10  hydration_level       1000 non-null   int64
 11  bmi                   1000 non-null   float64
 12  risk_score            1000 non-null   float64
dtypes: float64(7), int64(5), object(1)
memory usage: 101.7+ KB

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.nunique()

user_id                 1000
date                    1000
weight                   984
height                   982
blood_glucose            964
physical_activity        925
diet                       2
medication_adherence       2
stress_level               3
sleep_hours              927
hydration_level            2
bmi                      257
risk_score               899
dtype: int64

In [15]:
df['age'].unique()

KeyError: 'age'

In [16]:
df['outcome'].unique()

KeyError: 'outcome'

In [18]:
df['blood_glucose'].unique()

array([112.992869  , 134.21925317, 108.30320316, 127.68153881,
        70.        , 148.53174829, 140.04821901, 107.31645476,
       166.36982674, 177.50280551,  75.69760543, 109.49100886,
       109.23430601, 102.40387596, 173.17899368, 132.24695445,
       129.41940635, 165.41672121,  90.42966421, 142.39730521,
       151.09507752, 194.42634383,  87.64718404, 147.35398179,
       212.02044726, 189.55785412, 148.38637661, 120.33455257,
       172.28490387, 101.05815201, 159.05431077, 160.21880637,
       182.4083963 , 250.38640156, 155.69663869, 119.64145497,
       138.97702751, 112.21147476, 123.62870248, 119.03646408,
       146.09419488, 107.1032027 , 184.84122669, 140.0082826 ,
       139.62798715, 126.88421134, 146.20762735, 173.00393059,
       105.31479137, 113.67534044, 127.85095885,  86.16516306,
       107.22968561, 120.95116506, 174.97556723, 150.50245316,
       147.74359645, 174.03591849, 134.50512846, 155.618594  ,
       135.87112988, 150.61449398, 116.6896537 , 134.62883351,
       196.90992544, 177.04861609, 178.61589938, 189.44522887,
       143.54630364, 147.8926283 , 115.29392418, 127.35708576,
       164.63084599, 188.15537749, 134.42214897, 121.99242941,
       140.02111835, 164.04826996,  82.24580735, 117.97852602,
        91.17150296, 119.67439209, 134.08878725, 121.87006364,
       198.09870138, 153.06979058, 152.01897438, 164.88828576,
        94.44667529, 181.5644715 , 136.96942854, 166.81922469,
        97.12571068,  77.84964936, 172.71558632, 155.05638104,
       103.91793783, 105.21347675, 185.01739138,  92.42352429,
       205.70691813, 103.97517061, 165.53567702, 126.85526097,
       164.12749724, 118.23543992, 133.48828376, 141.63676702,
        99.91250177, 169.63297382, 119.47145734, 130.85600339,
       100.22602502, 132.3588895 , 236.50461686, 171.38417152,
       139.22958481, 129.48436683, 140.89863571, 161.88476461,
        92.76748739, 184.57286779, 168.61525262, 168.72742903,
       157.53902955, 140.78466631, 166.91444944, 163.67256535,
       125.83837156, 117.05592908, 144.07425181, 201.96080606,
        90.43571697,  81.29898937, 146.59043365, 142.03550807,
       146.93366657, 149.75812792, 131.07190981, 199.59453754,
        75.96384086, 106.86011901, 135.86980959,  74.27244755,
       132.96582382, 206.45880663, 140.83545953, 149.22803623,
        89.59340939, 115.34554368, 124.99214479, 127.29139613,
       191.2657518 , 162.30764243,  95.54168172, 149.86019114,
       159.92886994, 185.60596154, 203.22162746,  99.39623233,
       107.56569955,  89.69688564, 130.63920564, 158.65433498,
       179.49338066, 136.96195905, 127.20609907, 146.07031969,
       106.59428393, 223.58154887,  75.69355892, 147.38962316,
       220.94424877, 140.27199378, 132.3984386 , 125.70218309,
       132.78433273, 194.91393899, 201.33734805,  83.0417139 ,
       129.33390683, 122.83022319, 163.54213079,  76.07502592,
       158.48690664, 220.97238493,  85.47303982, 147.5882467 ,
       113.52071289, 157.03548825, 140.7659111 , 114.34052364,
       159.51489139, 212.17392439, 132.36384833, 168.79031769,
        88.26908169, 101.74254493, 158.89625112, 199.36464114,
       154.22453395, 127.47767878, 139.97165622,  89.98369064,
       164.18061305, 175.29332249, 121.91638669, 121.19831409,
       150.63512919, 122.53121056, 137.35469541, 223.98887157,
       130.11897197, 125.66639392, 114.09832777, 169.76767886,
       132.75103307, 114.02507847, 192.85216129, 196.78412018,
       115.98305737, 180.30054759, 112.61480697, 171.62502397,
       175.70389353,  91.55312283, 169.23056476, 140.57092271,
       101.84242322, 123.71854748, 167.45273828, 144.23577812,
       163.37651922, 219.05762338,  77.43033553, 204.688503  ,
       144.1742375 , 104.04863807,  86.78745497, 132.43518437,
       176.86600448, 134.89803518, 200.44619721,  81.9529724 ,
       139.51644209,  89.90426222, 154.5452753 , 175.4754956 ,
       123.16952825, 147.95792587, 157.46954207, 156.1717902 ,
       189.43128767,  97.15785281, 167.20864422, 187.7003005 ,
       152.78607304, 119.83280676, 136.73909308, 153.90705934,
       120.51085744, 112.97167683, 141.3660967 ,  96.51016245,
        96.56699484, 167.17493132,  94.04823859, 166.65250004,
       158.50365171,  70.96773085, 112.89741391, 187.76437612,
       100.75337875, 121.42382951, 158.48243573, 171.33562037,
       129.93844456, 116.09959221, 196.89479447, 209.55598655,
       179.15432203, 143.4127257 , 107.66937113, 106.78222374,
       160.90056421, 156.73592884, 196.06394372, 166.0180037 ,
        79.87678793, 182.07790471, 100.07757491, 124.64114912,
       150.00800825, 219.82669959, 264.39674224, 164.26892237,
       132.67213525, 161.38022594, 175.50621703, 127.17329498,
       211.80845424, 149.20283037, 159.90972356, 166.63697008,
       156.86346442, 173.55762002, 115.30987254, 117.66792984,
        95.99383068, 157.58004922, 171.15746014, 158.31091465,
       206.97969733, 139.77615925, 166.74966622,  96.33196495,
       124.5160119 , 167.8215103 , 173.96408443, 128.24132209,
       137.13602993,  79.28505013, 125.71883197, 175.61532654,
       163.00820064, 160.02662886, 141.99094749, 140.28252635,
       113.58715442, 167.95313681, 156.83891778, 159.68075392,
       118.95860629, 183.88610847, 120.84650176, 105.48896944,
       167.73915648, 124.3194944 , 182.39745536, 164.68023798,
       167.34277293,  85.36177155, 188.47775942, 150.45002125,
       125.22891443, 145.73553869, 156.34611246,  98.82513967,
        85.89318857,  79.10563255, 184.507535  , 114.82946425,
       201.3491084 , 118.56794148,  71.7056817 ,  95.3390224 ,
       189.4324648 , 133.76407288, 118.06850814, 146.40072903,
       160.07130945, 184.69595264, 197.9399692 , 125.60925417,
        86.95809256, 123.46139356, 150.41122026, 101.44964295,
       101.7139634 , 153.75151526, 138.05390594, 141.31187982,
       109.66018661, 130.78397143, 103.03067423, 175.60793644,
       181.40997339, 102.81956559,  80.1388298 , 113.99904262,
       136.66248121,  82.01419121, 103.12560747,  99.84170512,
       148.29069318, 142.77377348, 111.13049787, 147.07283489,
       118.13279662, 129.13379559, 206.93808361, 193.61844207,
        88.01675052, 173.18929672, 172.45586218,  94.06946845,
       172.75110575, 201.51727674,  95.09820775, 103.29988716,
       180.70645867, 150.85981243, 162.05905101, 153.62356866,
       155.62783684,  86.94111487, 181.89270826, 186.7835997 ,
       130.82437024, 138.26092201,  78.7556999 , 160.57019024,
       162.88229767, 137.51235932, 184.97413439, 126.63691076,
       162.58423704,  99.21342645, 139.05791397, 133.02582968,
       149.01231688, 125.21892285, 134.74109617, 173.04188686,
       122.52943051,  75.73691597, 209.98335617, 195.25816315,
        88.3094922 , 167.58831221, 119.88100918, 150.53948861,
       151.76896516, 130.62368799, 108.64937338, 112.37835791,
       103.35232338, 106.72711167, 137.3128684 , 111.36960044,
       167.28208263, 199.48984621, 116.79787035, 149.57618002,
       159.98740441, 158.88009084, 143.03821072, 169.70729673,
       159.28995811,  90.49350311, 174.76624258, 175.49163349,
       109.46855583, 141.51751342, 167.33315971, 131.62744722,
       182.91912191, 234.55489978, 108.56055869,  84.75821587,
       152.15274382, 168.86250021, 130.76534505, 198.13042653,
        86.45576801, 167.71674492, 115.76556717, 208.77511625,
       219.70061413, 109.33373649, 118.01771456, 174.38351548,
       124.51477401, 138.18355128, 141.01553682, 139.44649016,
       112.41088904, 120.2750871 , 197.74528014,  89.73972423,
       172.52820747, 128.84148279, 128.80959326, 171.61487584,
       153.60205178, 162.82451989, 178.72738642, 126.74766467,
       115.51053062,  96.59397894, 106.9835788 , 257.96377701,
       189.78718323,  85.95702535,  87.10168173, 159.27464247,
       161.8905919 , 161.95535341, 129.80176826, 134.9818296 ,
       153.11518097, 143.43572025, 130.80801478, 105.94374263,
       147.00845676, 259.4103601 , 154.69926662, 127.45881255,
       176.87206008, 159.30751549, 156.80377962, 164.27402373,
       222.26174259,  94.76446259, 158.94528307, 102.9447548 ,
       162.22050585, 103.25253954, 123.30532746, 128.19640343,
       179.03266877, 176.73817776,  90.17130494, 142.19736444,
       111.61680581,  89.65980357, 131.31931798, 127.66068846,
       237.06865945, 157.31839301,  84.89529997, 117.40903983,
       180.85533182, 223.53771091,  76.56066751, 214.83860701,
       155.58456709, 105.26829072, 161.38516344, 140.13502026,
       153.11284691, 176.97080558,  99.44416191, 143.42748646,
       102.98301496, 150.21535023, 104.18614711, 123.67596643,
       100.16738421, 166.04544967, 174.33804467, 130.6151772 ,
       141.5295198 ,  82.05634341, 128.01293408, 137.99181532,
       244.83172364,  95.52131897, 198.56708955, 179.87435094,
       151.22545618, 210.34481937, 154.8842189 , 155.56636783,
       137.87517388, 188.9427553 , 183.85876935, 114.9729085 ,
        87.23011222, 131.8807745 , 107.99845742, 137.45901702,
       189.49752539, 121.7079338 , 138.28706475, 142.32090939,
       173.93723529, 115.73198821, 148.45134769, 188.00315826,
       120.3239021 , 164.78845784, 114.58550445,  92.41333364,
       115.02618441, 132.61898569, 115.81021342, 175.88264788,
       190.99500165, 166.06087965,  94.49257318, 131.94033864,
       139.73914739, 163.95177558, 166.73361955, 110.63304805,
       143.27982226, 158.29121618, 198.23289289, 168.18026159,
       171.5622675 , 143.35306512, 196.41836581, 156.39051184,
       105.55648359, 196.13479881, 167.9161309 , 122.27823915,
       120.8202813 , 151.86302181, 158.52739181, 147.89169063,
       152.45234694, 207.99829498, 182.86172609, 147.62542365,
       177.65242323,  98.69904386, 155.917082  , 212.37225399,
       131.27816418, 106.09464286, 113.91644446,  96.41467851,
       108.60952367, 125.17967606,  83.77731923, 140.62473336,
       176.09108695, 103.68975279, 200.77135695, 160.43168354,
       181.22322342, 113.68661785, 174.18100908,  96.32264398,
       175.60990003, 146.87357359, 162.1300488 ,  92.97621578,
       104.19720631, 163.88912873, 102.06607983, 158.52825168,
        85.31448774, 173.92696851,  90.69906741, 162.09199751,
       165.02523735, 112.12912726, 163.28106268, 150.41769053,
       118.44632575,  99.65781264, 153.98600189,  77.40788915,
       143.81376798, 129.46207136, 167.16571102, 127.91818002,
       126.82208855, 169.27482817, 153.40232116, 152.64623829,
       158.77070359,  78.57711507, 170.2715472 , 164.49875176,
        99.33267486, 130.23678105, 138.42770849, 134.62012862,
       153.35439866, 197.25467127, 183.27066911,  87.51123226,
       164.88279961, 193.15733278, 155.47234083, 183.63921701,
       220.49081783, 180.94838184, 149.97234383, 181.80353896,
       145.79551332, 140.95612173, 125.94343057, 202.53653435,
       107.26285336, 201.29470899, 159.99456495,  84.02775301,
       154.70597172, 165.02032067, 175.40925932, 116.30576177,
       144.94190784, 218.16629735, 119.77013183,  97.64369652,
       199.2665361 , 218.50348762, 140.14782687, 180.45852142,
       193.65903662, 110.3006307 , 120.58776659, 189.23498053,
       207.40057115, 162.51523441, 104.80742586, 219.48244447,
       118.76116409, 126.59448875, 153.69351338, 202.16641683,
       174.15903906, 156.59462001, 158.5315412 , 141.74058675,
       162.32558058, 128.13570164, 149.6528774 ,  93.95943666,
       155.45293271, 131.82115116, 210.21902793, 202.92078901,
       121.36777724, 133.96649154, 137.04209738, 121.93362095,
       147.80099936, 109.66871724,  94.7753866 , 164.90844896,
       165.18118337, 107.82736961, 175.81421723, 114.73689083,
       150.12660952, 172.8137605 , 138.65549741, 158.18963649,
       119.34281424, 132.14133666, 131.76562276, 110.13686614,
       132.92903348,  78.05526805, 120.35385011, 128.60498027,
       129.7528099 , 130.34010217, 137.52943201, 159.17766072,
       174.98068297, 114.00939093,  91.87196578,  98.31822351,
       120.51188315, 125.92314729, 109.20015735,  88.15533343,
       121.7551669 , 147.2570648 , 163.80117863, 117.70307788,
       123.48008711, 102.93206765, 138.74243319, 106.06285463,
       162.92511253, 125.6148131 , 152.04429357, 147.35338065,
       247.72134656, 153.99200098,  99.83781613, 136.18143012,
       136.77601003, 106.67775772, 176.61561102, 118.01838902,
       135.32936337, 114.57768634, 209.55405407, 127.15028936,
       213.30228174, 172.56607048, 159.28266909, 154.74932589,
       155.75189193, 128.84466423, 173.80631885, 138.04411266,
        83.79240613, 137.90382198, 208.16422065, 189.87566862,
       137.51983963, 178.05797108, 125.33971919,  71.84513653,
       103.02136047, 202.51555074, 129.04027673, 130.26464082,
       128.00647215, 216.16546358, 205.03835661, 228.75120934,
       133.63819158, 151.82497955,  79.33429802, 199.07737704,
        93.28881795, 148.67102255,  96.10789889, 116.44532693,
       106.50950276, 115.68498957, 118.43509187, 118.0692482 ,
       173.33335647,  95.80548828, 148.82165708, 188.71836609,
       119.47214542, 111.28324437, 130.77901499, 187.18900833,
       147.76430524, 118.75142822, 159.35506605,  95.90831401,
       167.25438042, 156.34429231, 127.68766115, 106.45656806,
       104.53276311, 161.39269345, 189.1592201 , 114.50769012,
       158.33546814, 116.61529077, 138.75764269, 103.61266332,
       102.53974501, 113.28881774, 151.68770913, 132.50683926,
       115.72539289, 158.30746344, 120.01079295, 118.95008574,
       195.53351113, 124.59912753, 155.31955939, 145.6502856 ,
       170.72828867, 148.61586022, 160.33074559, 297.04950826,
       208.98786599, 128.50209922, 151.49315618, 138.17951019,
       123.03054666, 117.20668287, 153.18034942,  79.31305213,
       170.0231667 , 123.3522238 ,  94.79722644, 121.99948568,
       190.28596867, 118.58659652, 154.33814473, 110.76174897,
       170.316874  , 167.42030955, 213.94435333, 132.97744218,
       166.74619219, 143.92270158, 191.83487127, 111.2467045 ,
       169.80021252, 132.21210816, 137.43247292, 143.67009938,
       150.08961586, 135.35083828, 148.58852733, 203.1247223 ,
       179.41798742, 174.7661837 , 121.77841896, 104.43036687,
       178.21202233, 175.0418717 , 198.90682703, 115.84077496,
       130.81805379,  74.4206335 , 124.30115576, 179.86282042,
       121.34018483, 165.61919181, 132.37987576, 152.96228113,
        94.09234441, 143.40837799, 132.52415367,  74.78107025,
       188.23978066, 171.09629411, 158.66683928, 200.84024909,
       102.04333917, 209.89452792, 177.28766257, 130.53778851,
       185.42480589,  95.7482595 , 107.01943354, 115.65641107,
       118.84089168,  97.73769429, 188.92332268, 129.64582399,
       154.10019873, 117.18594534, 150.80229434, 137.25463816,
        85.26739845, 219.49103997, 176.45450889, 144.23015165,
       190.54826711, 106.1473609 , 161.73917515, 147.99241735,
       150.56080325, 190.89414   , 169.29968411, 151.54894651,
        73.80450255, 101.59814819, 135.09164266, 143.73489497,
        94.79185101, 236.46706702, 200.65576221, 164.08473282,
       142.88147445, 131.5116412 , 101.9232616 , 143.09922074,
       150.31010161,  90.32957698, 153.36705669, 133.78963805])

In [19]:
df['bmi'].unique()

array([22.9, 21.1, 27.4, 34.7, 21.2, 22. , 29.3, 26.2, 19.3, 28.8, 18.8,
       21.3, 20.2, 15.5, 12.6, 20.8, 20.5, 20.3, 16.1, 30. , 24.7, 24.6,
       13.3, 17.6, 23.6, 18.2, 25.8, 19.7, 25.7, 21.8, 41.6, 23.1, 17.4,
       30.2, 15. , 29.4, 16.8, 16.9, 22.4, 23.2, 26.5, 20.9, 22.8, 18.5,
       36.1, 12.9, 27.9, 19.6, 26.6, 31.6, 31.5, 19.9, 19.8, 24.4, 30.6,
       29.9, 16.2, 29.7, 35.8, 27.6, 20. , 30.5, 23.8, 37.8, 12.4, 23.9,
       24.1, 27.2, 33.1, 17.1, 19.2, 20.6, 25.2, 22.1, 27.5, 24.9, 18.9,
       20.4, 25.5, 32.8, 15.1, 28.3, 17.8, 31.7, 28.6, 14.6, 23.5, 22.2,
       34.9, 18.3, 29.5, 25. , 17. , 19.5, 22.7, 40.9, 18.4, 23.3, 15.6,
       23.4, 25.3, 28.9, 16.4, 26.3, 24.8, 26.1, 28.2, 20.7, 22.5, 28.5,
       33.4, 22.3, 21.4, 36.8, 28.7, 35.9, 24.5, 26. , 31.9, 18. , 28.1,
       32.1, 43.8, 26.9, 32.4, 25.1, 30.1, 18.6, 21.6, 33.8, 15.7, 29.1,
       34.1, 32.7, 31.8, 21.9, 24. , 19.4, 41.9, 14. , 30.3, 19. , 21.7,
       38.9, 11.5, 21. , 24.2, 32.5, 45.2, 14.2, 28.4, 23.7, 13. , 18.7,
       28. , 34.6, 16.7, 16. , 38.8, 16.6, 27. , 16.5, 26.7, 27.7, 30.8,
       31. , 20.1, 33.2, 33.9, 25.6, 17.5, 21.5, 15.2, 29.8, 39.9, 31.1,
       29.6, 24.3, 22.6, 37.6, 35.6, 31.2, 38.3, 16.3, 10.9, 29. , 13.9,
       18.1, 35.2, 17.2, 15.4, 31.3, 40.1, 15.3, 33.7, 14.5, 13.6, 27.8,
       35. , 14.9, 36. , 44.8, 13.1, 39.8, 15.9, 36.5, 17.7, 13.5, 12.8,
       27.1, 23. , 34. , 27.3, 33.5, 30.7, 36.9, 13.7, 17.9, 38.4, 33.3,
       25.4, 35.7, 38. , 34.4, 38.1, 14.8, 14.4, 33. , 37.7, 26.4, 19.1,
       32. , 30.9, 14.1, 25.9, 32.3, 37.2, 15.8, 32.6, 37.3, 13.4, 37.4,
       32.9, 31.4, 37.1, 37. , 35.1, 41. , 41.7, 36.4, 26.8, 32.2, 38.2,
       17.3, 34.3, 34.2, 12.7])

In [20]:
df.isin([0]).sum()

user_id                   0
date                      0
weight                    0
height                    0
blood_glucose             0
physical_activity        76
diet                    396
medication_adherence    307
stress_level            373
sleep_hours               0
hydration_level         290
bmi                       0
risk_score                2
dtype: int64

In [21]:
(df['blood_glucose']==0).sum()

np.int64(0)

**Selecting and filtering data**

---

In [22]:
df[['blood_glucose','bmi']]

     blood_glucose   bmi
0       112.992869  22.9
1       134.219253  21.1
2       108.303203  27.4
3       127.681539  34.7
4        70.000000  21.2
..             ...   ...
995     143.099221  20.1
996     150.310102  33.7
997      90.329577  30.6
998     153.367057  21.7
999     133.789638  29.7

[1000 rows x 2 columns]

In [24]:
df[df['weight']>50]

,user_id,date,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
0,1,2021-01-01,77.450712,183.993554,112.992869,0.000000,1,0,1,6.342317,1,22.9,38.000000
1,2,2021-01-02,67.926035,179.246337,134.219253,12.792300,0,1,2,10.658122,1,21.1,39.162310
2,3,2021-01-03,79.715328,170.596304,108.303203,21.727889,1,1,0,5.997832,1,27.4,31.481633
3,4,2021-01-04,92.845448,163.530632,127.681539,67.753753,1,0,1,7.958814,1,34.7,45.000000
4,5,2021-01-05,66.487699,176.982233,70.000000,41.131062,1,1,0,6.774707,1,21.2,4.717234
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-12-26,65.783496,180.701502,143.099221,30.569152,0,1,0,6.363948,1,20.1,17.357712
996,997,2023-12-27,96.965298,169.734787,150.310102,0.000000,0,0,1,7.736771,1,33.7,73.000000
997,998,2023-12-28,79.612643,161.181253,90.329577,23.594044,0,0,1,4.000000,1,30.6,70.921787
998,999,2023-12-29,61.432315,168.369330,153.367057,62.867563,1,1,2,7.035861,1,21.7,10.000000
999,1000,2023-12-31,78.588742,162.550974,133.789638,37.212958,0,1,2,6.166246,1,29.7,40.696761

In [26]:
df[(df['weight']>50 & df['risk_score']==1)]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [27]:
#Access rows by index(iloc)
df.iloc[0:5]

,user_id,date,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
0,1,2021-01-01,77.450712,183.993554,112.992869,0.000000,1,0,1,6.342317,1,22.9,38.000000
1,2,2021-01-02,67.926035,179.246337,134.219253,12.792300,0,1,2,10.658122,1,21.1,39.162310
2,3,2021-01-03,79.715328,170.596304,108.303203,21.727889,1,1,0,5.997832,1,27.4,31.481633
3,4,2021-01-04,92.845448,163.530632,127.681539,67.753753,1,0,1,7.958814,1,34.7,45.000000
4,5,2021-01-05,66.487699,176.982233,70.000000,41.131062,1,1,0,6.774707,1,21.2,4.717234

In [29]:
#sorting and grouping
df.sort_values(by='weight',ascending=False).head()

,user_id,date,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
209,210,2021-08-17,120.000000,187.495767,139.971656,39.024506,1,1,2,7.138736,0,34.1,45.243873
478,479,2022-06-08,116.183212,161.125078,86.455768,53.071807,0,1,1,8.551293,1,44.8,41.732048
179,180,2021-07-16,110.802537,158.964107,140.271994,40.312562,1,0,0,9.223397,1,43.8,49.921860
755,756,2023-04-07,109.485731,183.736585,121.933621,0.000000,0,0,1,9.245784,1,32.4,78.000000
654,655,2022-12-18,108.600397,173.384838,113.686618,32.987270,0,1,0,8.282121,0,36.1,46.753183

In [31]:
df.sort_values(by='weight',ascending=False).tail()

,user_id,date,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
382,383,2022-02-23,40.0,191.573082,153.751515,34.251481,1,1,2,6.002547,0,10.9,31.437130
262,263,2021-10-14,40.0,175.387560,189.431288,11.907713,1,0,0,4.238332,1,13.0,46.392538
236,237,2021-09-16,40.0,186.777008,140.570923,50.148879,1,1,0,8.229824,1,11.5,12.462780
74,75,2021-03-23,40.0,179.962668,115.293924,15.339340,1,1,1,7.925875,0,12.4,33.398198
991,992,2023-12-22,40.0,177.542913,164.084733,20.574725,1,1,1,4.999174,0,12.7,36.827582

**GROUP BY AND AGGREGATE**

In [33]:
df.groupby('weight').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [34]:
df['bmi'].mean()

np.float64(24.3855)

In [35]:
df['blood_glucose'].mean()

np.float64(140.818898915992)

In [36]:
df['blood_glucose'].median()

139.98996940683102

In [37]:
df['weight'].mode()

0    40.0
Name: weight, dtype: float64

In [38]:
df['weight'].value_counts()

weight
40.000000    17
69.638124     1
72.971271     1
67.834594     1
61.395070     1
             ..
57.617542     1
65.179212     1
76.193972     1
61.544132     1
54.909739     1
Name: count, Length: 984, dtype: int64

In [39]:
df['weight'].std()

14.467164994484909

In [41]:
df.corr()

ValueError: could not convert string to float: '2021-01-01'